server:
  port: 7002


#Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否向eureka注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/,http://localhost:7003/eureka/
